// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the DIRECT connection for CLI operations (migrate/db push).
    // The pgbouncer transaction-pooler (DATABASE_URL / :6543) hangs Prisma's
    // migration engines, so we route CLI commands to the direct :5432 URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
